### ISSUE TITLE
auto closing if chosen point is less than x meters from begin point away.

### ISSUE THREAD

**Issue by mirlip** [s-leger/blenderPolygons#14]
When drawing a wall, it would be helpfull to close the wall automatically and finish the operator if you click on the start point or near it. Maybe a default threshold of 2cm could be ok? Or just leave it as the snap system allows to exactly match the start point. I think both solutions are good.

**Comment by s-leger** [comment]
Agree with this, 
also think about for closed fences.

**Comment by s-leger** [comment]
Done, find it in archipack_dev branch

**Comment by mirlip** [comment]
works great
