### ISSUE TITLE
exact manipulation of parametric objects in UI

### ISSUE THREAD

**Issue by mirlip** [s-leger/blenderPolygons#3]
Hi s-leger,

Really impressive addon. Would it be possible to allow giving exact values with keyboard while grabbing the arrows (in manipulate mode)? Maybe by making it work like the tweak select for grab. If you click and move on an object in blender, it will call the grab operator, you can then release the select button and start typing "x 30" for example to constrain on X and move on 30 units. The same would be great for your distance and angle handles. Releasing the mouse button could allow to take input from keyboard to constrain and give exact values.

Regards

**Comment by s-leger** [comment]
Hi mirlip,

Great idea here, will investigate to find if someone in other addon allready have a piece of code to handle keyboard based values input.

For precision currently there is an undocumented feature with ALT pressed while manipulating enable snapping.

Currently working on snap feature for wall segments based on np_station (at manipulate time and at create time).

**Comment by mirlip** [comment]
Hi @s-leger ,

Thanks for the quick answer. I would suggest to change alt to ctrl. It would make it consistent with Blender's own snapping keymap.
If I'm right, "snap utilities line" in official addons has a piece of code to handle keyboard input and display it in the 3D view header with also navigation to modify the value with arrows, etc.

**Comment by s-leger** [comment]
Thank you for pointing out snap utilities line, seem a good basis.
For snap key, will get it from blender preferences if available, so anyone may use her own.

**Comment by s-leger** [comment]
NP_station based snap tool allow keyboard entry, so should fix this issue for walls at least.
Will see for others if i find an easy / efficient way to do this as mixing keaboard and mouse inputs definitely seem not ultimate solution.

**Comment by mirlip** [comment]
mechanical blender (https://github.com/mauge123/mechanical-blender) allows to click on the 3D view dimension/angle value to modify it, like in N or properties panels. Together with the current clickable arrow, I think it's the most intuitive way for editing dimensions and angles.

**Comment by s-leger** [comment]
Great idea !
Together with the snap utilities keyboard interpreter, should not be too hard to implement.

**Comment by mirlip** [comment]
You mean parametric positioning of windows related to each other? It would be awesome :)

**Comment by s-leger** [comment]
Yes, sounds not impossible.
Implemented keyboard entry right on selectables labels and does work quite well.
Still need to fine tune sensitive area over text so they are "selectable" and "hover" in a predictible way.

**Comment by mirlip** [comment]
awesome :)

**Comment by mirlip** [comment]
it works great :)
