### ISSUE TITLE
allow values under -1 and above 1 for offset of walls.

### ISSUE THREAD

**Issue by mirlip** [s-leger/blenderPolygons#4]
The solidify modifier allows values outside of  [-1;+1] (there is a soft limit at those values, but inputing 4 for example is allowed). It would be great to allow those values in the N panel of your addon.

**Comment by s-leger** [comment]
Hi,
The 2d part of the code is also able to handle offset (at some extends) think about an arc based wall and offset greater than radius ...

Investigation are to be done as solidify with greater values may result in degenerated model too witch is an issue for boolean operations.

The point with solidify method is also handling manipulators location and limits.

**Comment by mirlip** [comment]
Hi,

of course, the user has to be carefull with such high values. I would let the soft limit at -1 to 1 but allow to type other values just like in the modifier panel.

**Comment by s-leger** [comment]
Wall meshing realy needs some steroids on it, solidify is by far too generic to handle real world walls.
issues with solidify include:
- top faces with lateral slope when height and direction change. 
- unable to setup width per segment

**Comment by mirlip** [comment]
Completely agree. A way to also generate the plates between 2 building levels that have different shapes would also be really needed to create modern houses and buildings.

**Comment by s-leger** [comment]
Height as per segment is in the pipe, 
currently you may setup up to 32 different height along a single segment to fit a roof for sample.

**Comment by s-leger** [comment]
Will not be part of 1.2 release, but in the pipe for next one.
