### ISSUE TITLE
only one selectable bounding box for parametric objects

### ISSUE THREAD

**Issue by mirlip** [s-leger/blenderPolygons#6]
Hi @s-leger ,
It would help a lot to have only the bounding box selectable, to ensure that all the parts are always moved together.

**Comment by s-leger** [comment]
Editing sub-objects allow rotations to open/close windows and doors.
By default the translation is locked on subs, i think translation is only allowed for rail type windows panels.
If i recall correctly (may be wrong at this), holes objects are not selectable.
So if you end up in not selecting the right object, there is the edit params button to select parent in the n panel.

**Comment by mirlip** [comment]
That can indeed be helpful to be able to modify parametric objects in UI using blender's operators. I must say I'm very impressed by your system. It's highly flexible and robust. Modifying the width, height, etc. of a window work and keeps the custom rotation of the different parts. Awesome. So forget what I said. Users will just have to learn which part to select for duplication and transformation of the whole parametric object.

**Comment by s-leger** [comment]
Youre advice is precious as it show what's important to provide in the doc.
